Cleanups
teia-community/teia-ui-legacy pull request #7
Opened 2022-02-16 20:40 UTC by xat

just a bunch of smaller cleanups. hopefully didn't remove anything that is actually needed :)

2022-02-17 10:33 UTC, xat commented
removed the commits with the formatting and the code cleanup.

2022-02-19 18:34 UTC, melMass requested changes
Besides the `gh-pages` thing it's all good for me!
I did not know there was that many unused packages 👍

2022-02-19 18:34 UTC, melMass commented on Dockerfile
> -FROM node:latest
I'm not sure if @jmagly is not using the DockerFile somehow?

2022-02-19 18:34 UTC, melMass commented on gh-pages/html-preview/index.html
> -<!DOCTYPE html>
All the files in `gh-pages` are used for previews (of interactive tokens).
Maybe this could be moved to a branch or something later on though

2022-02-19 18:34 UTC, melMass commented on gh-pages/html-preview/index.html
> -<!DOCTYPE html>
But it could also be rethought all together

2022-02-24 15:32 UTC, xat commented on gh-pages/html-preview/index.html
> -<!DOCTYPE html>
i re-added the gh-pages folder

2022-02-25 16:50 UTC, melMass approved these changes
All good to me, that DockerFile could be recreated easily if needed but I don't think it has any use

2022-02-25 16:52 UTC, merged